# Generated by Django 5.0.2 on 2024-02-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhw1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
